import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextUIProviderWrapper from './providers/NextUIProviderWrapper'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'QRCODE MENU',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
          <NextUIProviderWrapper>
              <NavBar />
              {children}
          </NextUIProviderWrapper>
      </body>
      </html>

  )
}
